<?php

/**
 * Implements hook_entity_info()
 */
function personal_information_entity_info() {
  return [
    'personal_information' => [
      'label' => t('Personal Information'),
      'controller class' => 'EntityAPIController',
      'entity class' => 'Entity',
      'base table' => 'personal_information',
      'entity keys' => [
        'id' => 'pid',
      ],
      'module' => 'personal_information',
    ],
  ];
}

/**
 * @param $pid
 * @param array $conditions
 *
 * @return \Entity|null
 */
function personalInformationLoad($uid, array $conditions): ?Entity {
  $result = entity_load('personal_information', $uid, $conditions);
  $personalInformationEntity = reset($result);
  return $result ? $personalInformationEntity : NULL;
}

/**
 * Implements hook_form_alter()
 */
function personal_information_form_user_profile_form_alter(&$form) {
  $user = $form['#user'];
  $personalInformationEntity = personalInformationLoad(FALSE, ['user_id' => $user->uid]);


  $form['personal_information']['phone'] = [
    '#type' => 'textfield',
    '#title' => t('Phone number'),
    '#default_value' => $personalInformationEntity === NULL ? '' : $personalInformationEntity->phone,
  ];
  $form['personal_information']['user_name'] = [
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#default_value' => $personalInformationEntity === NULL ? '' : $personalInformationEntity->user_name,
  ];
  $form['personal_information']['surname'] = [
    '#type' => 'textfield',
    '#title' => t('Surname'),
    '#default_value' => $personalInformationEntity === NULL ? '' : $personalInformationEntity->surname,
  ];

  $form['actions']['submit']['#submit'][] = 'customPersonalInformationUpdate';

}

/**
 * @param $form
 * @param $form_state
 */
function customPersonalInformationUpdate($form, &$form_state) {
  $user = $form_state['user'];
  $personalInformationFormData = $form_state['values'];

  $personalInformationEntity = personalInformationLoad(FALSE, ['user_id' => $user->uid]);
  if ($personalInformationEntity === NULL) {
    $personalInformationEntity = entity_create('personal_information', []);
  }

  $personalInformationEntity->user_name = trim(htmlspecialchars($personalInformationFormData['user_name']));
  $personalInformationEntity->surname = trim(htmlspecialchars($personalInformationFormData['surname'] ));
  $personalInformationEntity->phone = trim(htmlspecialchars($personalInformationFormData['phone']));
  $personalInformationEntity->user_id = $user->uid;
  $personalInformationEntity->save();
}

/**
 * Implements hook_entity_property_info_alter().
 */
function personal_information_entity_property_info_alter(&$info) {

  $properties = &$info['personal_information']['properties'];
  $properties['user_id']['label'] = t('Personal Information');
  $properties['user_id']['type'] = 'user';
  $properties['user_id']['description'] = t('Reference to ERP Country entity.');
}

/**
 * Implements hook_views_data_alter().
 */
function personal_information_views_data_alter(&$data) {

  $data['users']['uid']['relationship'] = [
    'label' => t('Personal information'),
    'base' => 'personal_information',
    'base field' => 'user_id',
    'relationship field' => 'uid',
  ];
}
