<?php
/**
 * Implements hook_menu().
 */
function rn_page_menu() {
  $items['drupal-test-task'] = [
    'title' => 'Task',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['rn_page_tables_page'],
    'access callback' => TRUE,
  ];
  return $items;
}

/**
 * Implements hook_theme().
 */
function rn_page_theme() {
  return [
    'users' => [
      'render element' => 'form',
      'file' => 'rn_page.theme.inc',
    ],
  ];
}

function rn_page_get_all_users() {
  return db_select('users', 'u')
    ->extend('PagerDefault')
    ->fields('u', ['uid', 'name'])
    ->range(0, 50)
    ->execute()
    ->fetchAllAssoc('uid');
}

/**
 * Example tables page.
 */
function rn_page_tables_page() {

  $header = [
    ['data' => t('id'), 'field' => 'u.id'],
    ['data' => t('Type'), 'field' => 'u.name'],
    t('Action'),
  ];

  $users = rn_page_get_all_users();
  $form['user_table'] = [
    '#type' => 'container',
    '#theme' => 'users',
    '#header' => $header,
  ];

  foreach ($users as $uid => $user) {

    $form['user_table'][$uid]['id'] = [
      '#markup' => $user->uid,
    ];

    $form['user_table'][$uid]['name'] = [
      '#markup' => $user->name,
    ];

    $form['user_table'][$uid]['link'] = [
      '#type' => 'link',
      '#title' => t('Edit'),
      '#href' => 'user/' . $uid . '/edit',
    ];

    $form['pager']['#markup'] = theme('pager');
  }
  return $form;
}
